name: Deploy to AWS with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
            # 1. Заходим в домашнюю директорию
            cd ~
            
            # 2. Удаляем старую папку app, чтобы скачать всё заново (чистовик)
            sudo rm -rf app
            
            # 3. Скачиваем твой проект из GitHub на сервер
            git clone https://github.com/Yusif2603/MyDevops.git app
            
            # 4. Переходим в скачанную папку
            cd app

            # 5. Останавливаем старые контейнеры, чтобы не мешались
            sudo docker-compose down || true
            sudo docker stop my-web-site || true
            sudo docker rm my-web-site || true

            # 6. ЗАПУСК! Собираем и поднимаем всё
            sudo docker-compose up --build -d
